//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.ParkingAdvice.MVP.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacionamiento()
        {
            this.HistoricoEstacionamiento = new HashSet<HistoricoEstacionamiento>();
        }
    
        public byte Id { get; set; }
        public Nullable<byte> Numero { get; set; }
        public Nullable<byte> EstadoEstacionamientoId { get; set; }
        public Nullable<int> ZonaEstablecimientoId { get; set; }
    
        public virtual EstadoEstacionamiento EstadoEstacionamiento { get; set; }
        public virtual ZonaEstablecimiento ZonaEstablecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoEstacionamiento> HistoricoEstacionamiento { get; set; }
    }
}
