//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.ParkingAdvice.MVP.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoEstacionamiento
    {
        public int Id { get; set; }
        public byte EstacionamientoId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Estacionamiento Estacionamiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
