//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.ParkingAdvice.MVP.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamientoDFEntities : DbContext
    {
        public EstacionamientoDFEntities()
            : base("name=EstacionamientoDFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Establecimiento> Establecimiento { get; set; }
        public virtual DbSet<Estacionamiento> Estacionamiento { get; set; }
        public virtual DbSet<EstadoEstacionamiento> EstadoEstacionamiento { get; set; }
        public virtual DbSet<HistoricoEstacionamiento> HistoricoEstacionamiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ZonaEstablecimiento> ZonaEstablecimiento { get; set; }
    }
}
