//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.ParkingAdvice.MVP.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaEstablecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZonaEstablecimiento()
        {
            this.Estacionamiento = new HashSet<Estacionamiento>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal Latitud { get; set; }
        public decimal Logitud { get; set; }
        public int CantidadEstacionamientos { get; set; }
        public int CantidadEstacionamientosUsados { get; set; }
        public int EstablecimientoId { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estacionamiento> Estacionamiento { get; set; }
    }
}
